name: Test a pull request

on: 
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: |
        make requirements
        # make test
    - name: Dockerhub login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag flvbssln/roe_deepnote:v1